# Path to your oh-my-zsh installation.
export ZSH=/home/stefanozzz123/.oh-my-zsh

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=15

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd/mm/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# User configuration

export PATH="/usr/lib/ccache/bin:/opt/bin:/usr/bin/eclipse:/usr/bin/sublime_text_2:/bin:/usr/bin"
export LDPATH="${LDPATH}"
export MANPATH="${MANPATH}"
export INFODIR="${INFODIR}"
export PAGER="less"
export CONFIG_PROTECT="${CONFIG_PROTECT}"
export CONFIG_PROTECT_MASK="${CONFIG_PROTECT_MASK}"
export TERM="xterm-256color"
export MANPATH="/usr/local/man:$MANPATH"

#Oh my zsh script
source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8
#
export EDITOR="vim"

# Compilation flags
export ARCHFLAGS="-O2 -pipe -march=native -mtune=native"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

#Syntax Highlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

#Left prompt
PROMPT="%{$fg_bold[red]%}(%m)%{$reset_color%} %{$fg_bold[green]%}%n%{$reset_color%} on %{$fg_bold[blue]%}%~%{$reset_color%} %{$fg_bold[yellow]%}➜ %{$reset_color%}"
#Right prompt
RPROMPT="%{$bg[yellow]%}%{$fg_bold[black]%}{return: %?}%{$reset_color%} %{$bg[blue]%}%{$fg_bold[yellow]%}[%l]%{$reset_color%}"

alias esync="sudo emerge --sync "
alias eupg="sudo emerge --ask --verbose --update --deep --with-bdeps=y --newuse @world"
alias eget="sudo emerge --ask --verbose "
alias edel="sudo emerge --unmerge "
alias ecleandep="sudo emerge --depclean && sudo revdep-rebuild || echo 'Something was wrong'"
alias esearchdesc="emerge --searchdesc "
alias esearch="emerge --search "
alias makeconf="sudo vim /etc/portage/make.conf"
alias zshconf="vim $HOME/.zshrc"
alias awcfg="vim $HOME/.config/awesome/rc.lua"
alias awthmcfg="sudo vim /usr/share/awesome/themes/default/theme.lua"
alias wanip="curl ipecho.net/plain"

#My GitHub repository
mygithub="https://github.com/StefanoBelli"
