# Path to your oh-my-zsh installation.
export ZSH=/home/stefanozzz123/.oh-my-zsh
export TERM="xterm-256color"

#HISTFILE
HISTFILE=$HOME/.zsh_hist
HISTSIZE=50
SAVEHIST=30
setopt appendhistory autocd beep nomatch
unsetopt extendedglob
bindkey -e
# End of lines configured by zsh-newuser-install
# # The following lines were added by compinstall
zstyle :compinstall filename '/home/stefanozzz123/.zshrc'
zstyle ':completion:*' menu select
setopt completealiases
#
autoload -U compinit
compinit
# Uncomment the following line to use case-sensitive completion.
#CASE_SENSITIVE="false"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=15

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd/mm/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# User configuration

export PATH="/usr/bin/telegram:/usr/lib/ccache/bin:/opt/bin:/usr/bin/eclipse:/usr/bin/sublime_text_2:/bin:/usr/bin"
export LDPATH="${LDPATH}"
export MANPATH="${MANPATH}"
export INFODIR="${INFODIR}"
export PAGER="less"
export CONFIG_PROTECT="${CONFIG_PROTECT}"
export CONFIG_PROTECT_MASK="${CONFIG_PROTECT_MASK}"
export MANPATH="/usr/local/man:$MANPATH"

#Oh my zsh script
source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8
#
export EDITOR="vim"

# Compilation flags
export ARCHFLAGS="-Wall -O3 -pipe -march=native -mtune=native"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

#Syntax Highlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

STARTDATE="$(date +%H:%M) on $(date +%d/%m/%y)"
#banner here
#Left prompt
PROMPT="%{$fg_bold[red]%}(%m)%{$reset_color%} %{$fg_bold[green]%}%n%{$reset_color%} on %{$fg_bold[blue]%}%~%{$reset_color%} %{$fg[green]%}%#%{$reset_color%} "

RPROMPT="%{$bg[yellow]%}%{$fg_bold[black]%}{return: %?}%{$reset_color%} %{$bg[blue]%}%{$fg_bold[yellow]%}[%l]%{$reset_color%}"

#systemd init system
alias sdenable="sudo systemctl enable "
alias sdrestart="sudo systemctl restart "
alias sddisable="sudo systemctl disable "
alias sdstart="sudo systemctl start "
alias sdstop="sudo systemctl stop "
alias sdstatus="sudo systemctl status "
alias bootime="systemd-analyze time"
alias bootblame="systemd-analyze blame"
#Emerge - Portage interface
alias esync="sudo emerge --sync "
alias eupg="sudo emerge --ask --verbose --update --deep --with-bdeps=y --newuse @world"
alias eget="sudo emerge --ask --verbose "
alias edel="sudo emerge --unmerge "
alias ecleandep="sudo emerge --depclean && sudo revdep-rebuild || echo 'Something was wrong'"
alias esearchdesc="emerge --searchdesc "
alias esearch="emerge --search "
#Make.conf link
alias makeconf="sudo vim /etc/portage/make.conf"
#ZSH
alias zshconf="vim $HOME/.zshrc"
#Awesome
alias awcfg="vim $HOME/.config/awesome/rc.lua"
alias awthmcfg="sudo vim /usr/share/awesome/themes/default/theme.lua"
#External IP
alias wanip="curl ipecho.net/plain"
#OpenRC BSD-Style init system
alias rcadd="sudo rc-update add "
alias rcdel="sudo rc-update del "
alias rcshow="sudo rc-update -v show"
#RaspPi
alias pissh="ssh 192.168.2.110 -p 22 -l "
alias piscan="ssh root@192.168.2.110 -p 22 scan "
#OpenVPN to raspPi
alias piovpnrem="sudo openvpn --config $HOME/Documenti/pivpnrem.ovpn --writepid /var/run/ovpn.pid"
alias piovpnloc="sudo openvpn --config $HOME/Documenti/pivpn.ovpn --writepid /var/run/ovpn.pid"

#My GitHub repository
mygithub="https://github.com/StefanoBelli"

STARTDATE="$(date +%H:%M) on $(date +%d/%m/%y)"
banner(){
	#Next: CPU, RAM, Distro release...
	clear
	printf "\033[32mHello\033[0m: $USER"
	printf "\nMachine's \033[33mhostname\033[0m: "; cat /etc/hostname
	printf "Running \033[33mShell\033[0m: $SHELL\n"
	printf "Running \033[33mKernel\033[0m: $(uname -s -r)\n\n"
	printf "\033[34m *\033[0m Shell online from: \033[34m$STARTDATE\033[0m\n"
}

minecraft()
{
	printf "\033[32m*\033[0m Launching Minecraft...\n"
	java -jar /usr/bin/minecraft
	clear
	printf "\n\033[34m*\033[0m Bye!\n"
}

scr()
{
		  if [[ $1 == "start" ]];
		  then
					 printf "\033[32m*\033[0m Starting auto mode.... HDMI1 should work now.\n"
					 xrandr --auto
					 if [[ $2 == "split" ]];
					 then

								xrandr --output HDMI1 --right-of LVDS1 & 
					 elif [[ $2 == "" ]];
					 then
								echo ""
					 fi
		  fi
		  if [[ $1 == "stop" ]];
		  then
					 printf "\033[31m*\033[0m Stopping output to HDMI1\n"
					 xrandr --output HDMI1 --off
		  fi
}

banner

#End of ZSH configuration
