#Prompt and right prompt
PROMPT="(%m) %n %~ %#> "
RPROMPT="{return: %?}[%l]"

#HISTFILE
HISTFILE=$HOME/.zsh_hist
HISTSIZE=10
SAVEHIST=5
#setopt appendhistory autocd beep nomatch
unsetopt extendedglob
bindkey -e
## End of lines configured by zsh-newuser-install

export EDITOR="vim"

alias ovpnsrv="/usr/bin/openvpn --cd /etc/openvpn --config /etc/openvpn/server.conf --daemon openvpn@/etc/openvpn/server.conf --writepid /var/run/ovpn_srv.pid"

