#HISTFILE
HISTFILE=$HOME/.zsh_hist
HISTSIZE=50
SAVEHIST=30
setopt appendhistory autocd beep nomatch
unsetopt extendedglob
bindkey -e
# End of lines configured by zsh-newuser-install
# # The following lines were added by compinstall
zstyle :compinstall filename '/home/stefanozzz123/.zshrc'
zstyle ':completion:*' menu select
setopt completealiases
#
autoload -U compinit
compinit

export PATH="${PATH}"
export LDPATH="${LDPATH}"
export MANPATH="${MANPATH}"
export INFODIR="${INFODIR}"
export PAGER="less"
export CONFIG_PROTECT="${CONFIG_PROTECT}"
export CONFIG_PROTECT_MASK="${CONFIG_PROTECT_MASK}"
export TERM="xterm"
export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8
#
export EDITOR="vim"

# Compilation flags
export ARCHFLAGS="-O2 -pipe -march=native -mtune=native"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

#Left prompt
PROMPT="(%m) %n on %~ %# "
RPROMPT="{return: %?} [%l]"
