#Syntax Highlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

#Prompt and right prompt
PROMPT="(%m) %{$fg[red]%}%n %~ %#> "
RPROMPT="{return: %?}[%l]"

#aliases
alias eget="emerge --ask --verbose "
alias esearch="emerge --search "
alias esearchdesc="emerge --searchdesc "
alias exfupg="emerge --ask --verbose --deep --update --with-bdeps=y --newuse @world"
alias edel="emerge --unmerge "
alias ecleandep="sudo emerge --depclean && sudo revdep-rebuild || echo 'Something was wrong'"
alias makeconf="vim /etc/portage/make.conf"
alias zshconf="vim /root/.zshrc"
alias wanip="curl ipecho.net/plain"

