"Begin of vim config file
set shell=/bin/bash
set nocompatible "Not compatible with Vi settings
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'Markdown'
Plugin 'c.vim'
Plugin 'a.vim'
Plugin 'scrooloose/nerdTree'
Plugin 'syntastic'
Plugin 'Tagbar'
Plugin 'fugitive.vim'
" Plugin 'snipMate'
Plugin 'snippets.vim'
" Plugin 'git-diff'
Plugin 'clang-complete'
Plugin 'python-imports.vim'
Plugin 'Valloric/YouCompleteMe'

call vundle#end()            " required
filetype plugin indent on    " required
""""""""""""""""""""""""""""""""
set secure
set backspace=indent,eol,start
set nobackup "No backup
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching
set autoindent " indenting
set showcmd 
set cursorline
set tabstop=3
set softtabstop=3
set shiftwidth=3
set noswapfile " No swapfile 
set nowb
set wildmenu 
set modeline
set ls=2 
set number " left-side line counter
set t_Co=256color "Enable 256 colors terminal
set hlsearch "highlight matched 
set autowrite
set shortmess=a
set cmdheight=2

map Q gq
inoremap <F4> <C-x><C-o>
" Plugins bind
map pi :PluginInstall  
map ps :PluginSearch 
map pc :PluginClean 
map pl :PluginList

" Buffer delete map
map bd :bdelete

syntax on "Enable syntax
colorscheme brogrammer 
filetype plugin indent on 
autocmd FileType text setlocal textwidth=78

"Language interpreter/compiler execution
"C/GCC
"Python/python - env 
"Ruby/ruby 
"C++/G++/GCC-C++
"Shell/sh
autocmd FileType c map cc :!/usr/bin/gcc % -Wall -O2 -o 
autocmd FileType python map pyr :!/usr/bin/env python %
autocmd FileType ruby map rbr :!/usr/bin/ruby %
autocmd FileType cpp map cxx :!/usr/bin/g++ % -Wall -O2 -o 
autocmd FileType sh map shr :!/bin/sh %
"autocmd FileType asm map gas :!/usr/bin/as %

let g:PythonAutoAddImports = 1
let &path.="/usr/include,/usr/local/include"
let g:ycm_global_ycm_extra_conf = '/home/stefanoz/.ycm_extra_conf.py'
let g:ycm_confirm_extra_conf = 0
let g:ycm_python_binary_path = '/usr/bin/python3'
let g:ycm_min_num_of_chars_for_completion = 3
let g:ycm_auto_trigger = 1

set makeprg=/usr/bin/make\ -j\ 3

"Shortcuts
map <F2> :Tagbar
map <F3> :NERDTree
map <F5> :make 

" C / C++
let g:C_CCompiler = "gcc"
let g:C_CFlags = "-O2 -pipe -Wall"
let g:CplusCompiler = "g++"
let g:C_CplusFlags = "-O2 -pipe -Wall"

if has('langmap') && exists('+langnoremap')
				set langnoremap
endif

"If mouse is availible enable it
if has('mouse')
				set mouse=a
endif
let g:airline#extensions#tabline#enabled = 1
"End of vimrc
