"Begin of vim config file
set nocompatible "Not compatible with Vi settings

""""""""""""""""""""""""""""""""
set secure
set backspace=indent,eol,start
set nobackup "No backup
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching
set autoindent " indenting
set showcmd 
set cursorline
set tabstop=4
set softtabstop=4
set noswapfile " No swapfile 
set nowb
set wildmenu 
set modeline
set ls=2 
set number " left-side line counter
set t_Co=256color "Enable 256 colors terminal
set hlsearch "highlight matched 
set autowrite
set shortmess=a
set cmdheight=2

map Q gq
syntax on "Enable syntax
"colorscheme badwolf "badwolf 
filetype plugin indent on 
autocmd FileType text setlocal textwidth=78

"Language interpreter/compiler execution
"C/GCC
"Python/python - env 
"Ruby/ruby 
"C++/G++/GCC-C++
"Shell/sh
autocmd FileType c map cc :!/usr/bin/gcc % -Wall -O2 -o 
autocmd FileType python map pyr :!/usr/bin/env python %
autocmd FileType ruby map rbr :!/usr/bin/ruby %
autocmd FileType cpp map cxx :!/usr/bin/g++ % -Wall -O2 -o 
autocmd FileType sh map shr :!/bin/sh %

"Shortcuts
map <F2> :Tagbar
map <F3> :NERDTree

" C / C++
let g:C_CCompiler = "gcc"
let g:C_CFlags = "-O2 -pipe -Wall"
let g:CplusCompiler = "g++"
let g:C_CplusFlags = "-O2 -pipe -Wall"

if has('langmap') && exists('+langnoremap')
				set langnoremap
endif

"If mouse is availible enable it
if has('mouse')
				set mouse=a
endif
let g:airline#extensions#tabline#enabled = 1
"End of vimrc
