"Begin of vim config file
set shell=/bin/sh "Use a compatible shell 

set nocompatible "Not compatible with Vi settings
filetype off   "Vundle-required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'Markdown'
Plugin 'scrooloose/nerdTree'
Plugin 'syntastic'
Plugin 'Tagbar'
Plugin 'python-imports.vim'
Plugin 'jaxbot/semantic-highlight.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'ctrlp.vim'
Plugin 'Arduino-syntax-file'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'fatih/vim-go'
Plugin 'SirVer/ultisnips'
Plugin 'vim-ruby/vim-ruby'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'dag/vim-fish'
Plugin 'vhdirk/vim-cmake'
Plugin 'vim-scripts/perl-support.vim'
Plugin 'StefanoBelli/cmakeproj.vim'
Plugin 'stevearc/vim-arduino'
Plugin 'sudar/vim-arduino-syntax'
Plugin 'ycm-core/YouCompleteMe'
Plugin 'vim-airline/vim-airline'
Plugin 'arzg/vim-colors-xcode'

call vundle#end()            " required
filetype plugin indent on    " required
""""""""""""""""""""""""""""""""
set termguicolors
set secure
set backspace=indent,eol,start
set nobackup "No backup
set history=150		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching
set autoindent " indenting
set smartindent 
set showmatch
set antialias 
set showcmd 
set cursorline
set tabstop=4 softtabstop=4 shiftwidth=4 noexpandtab
set copyindent
set preserveindent
set noswapfile " No swapfile 
set nowb
set wildmenu 
set modeline
set t_Co=256 "Enable 256 colors terminal
set hlsearch "highlight matched 
set ignorecase
set smartcase
set autowrite
set shortmess=a
set autoread
set magic
set encoding=utf8
set ffs=unix,dos,mac
set foldmethod=manual
set lazyredraw

let c_cpp_cppcheck = 0
let make_jobs = 4

syntax on "Enable syntax highlight
let g:space_vim_dark_background = 233
colorscheme xcodelighthc

autocmd FileType text setlocal textwidth=78

"Language interpreter/compiler execution
autocmd FileType python map pyr :!/usr/bin/env python %
autocmd FileType ruby map rbr :!/usr/bin/ruby %
autocmd FileType sh map shr :!/bin/sh %

"CppCheck static analysis performed on post-write
if exists("c_cpp_cppcheck") && c_cpp_cppcheck
	autocmd BufWritePost *.cpp,*.h,*.hpp,*.cc,*.cxx :!/usr/bin/cppcheck %
				\ --std=c++11 
				\ --enable=warning,style,performance,information
				\ --platform=unix64 
				\ --language=c++ 
				\ -j4
				\ --includes-file.
	
	autocmd BufWritePost *.c,*.h :!/usr/bin/cppcheck %
				\ --std=c11 
				\ --platform=unix64
				\ --enable=warning,style,performance,information 
				\ --language=c
				\ -j4
				\ --includes-file=.
endif

"Make command 
set makeprg=/usr/bin/make\ -j\ make_jobs

"Python imports
let g:PythonAutoAddImports = 1

"Compilers -- generic
let fav_c_compiler = $CC
let fav_cpp_compiler = $CXX

"YCM
let g:ycm_global_ycm_extra_conf = '/home/ssynx/.ycm_extra_conf.py'
let g:ycm_confirm_extra_conf = 0
let g:ycm_python_binary_path = '/usr/bin/python3'
let g:ycm_server_python_interpreter = '/usr/bin/python3'
let g:ycm_min_num_of_chars_for_completion = 3
let g:ycm_auto_trigger = 1

augroup MyYCMCustom
  autocmd!
  autocmd FileType c,cpp let b:ycm_hover = {
    \ 'command': 'GetDoc',
    \ 'syntax': &filetype
    \ }
augroup END

"Syntastic 
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
let g:syntastic_python_python_exec = '/usr/bin/python'
let g:syntastic_python_checkers = ['pylint']
let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': [] }
let g:syntastic_c_check_header = 1
let g:syntastic_c_no_default_include_dirs = 1
let g:syntastic_c_compiler_options = ' -std=c99 -Wall -Wextra -Wshadow -W -pedantic'
let g:syntastic_c_compiler = fav_c_compiler
let g:syntastic_cpp_check_header = 1
let g:syntastic_cpp_no_default_include_dirs = 1
let g:syntastic_cpp_compiler_options = ' -std=c++11 -Wall -Wextra -Wshadow -W -pedantic'
let g:syntastic_cpp_compiler = fav_cpp_compiler
"let g:syntastic_c_include_dirs = [ 'include', 'include1' ]

"vim-go
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_interfaces = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_fmt_command = "goimports"
let g:go_play_open_browser = 0

"CtrlP
let g:ctrlp_map = '<c-p>'

"Airline 
let g:airline_powerline_fonts = 1

"AirlineThemes
let g:airline_theme = "light"

"UltiSnips 
let g:UltiSnipsExpandTrigger = "<F8>"
let g:UltiSnipsJumpForwardTrigger = "<C-f>"
let g:UltiSnipsJumpBackwardTrigger = "<C-b>"
let g:UltiSnipsEditSplit = "normal"

"Enable deoplete 
let g:deoplete#enable_at_startup = 1

"vim-cmake
let g:cmake_install_prefix = '/usr/bin'
let g:cmake_build_type = 'Debug'
let g:cmake_cxx_compiler = fav_cpp_compiler
let g:cmake_c_compiler = fav_c_compiler

"Various mapping
map <F2> :Tagbar<cr>
map <F3> :NERDTree<cr>
map <C-s> :SemanticHighlight<cr>
map <C-x> :SemanticHighlightRevert<cr>
map <C-e> :GitGutterEnable<cr>
map <C-d> :GitGutterDisable<cr>
map clpe :set paste<cr>
map clpd :set nopaste<cr>
map ssp :setlocal spell! spelllang=en_us<cr>
map sspd :setlocal nospell<cr>
map Q gq
map >> $ 
map pi :PluginInstall   
map ps :PluginSearch 
map pc :PluginClean 
map pl :PluginList<cr>

"Window movement / buffer ops.
" <C-k> : vim-go already uses <S-k>
nnoremap <S-h> <C-w>h
nnoremap <S-j> <C-w>j
nnoremap <C-k> <C-w>k 
nnoremap <S-l> <C-w>l
map osp :split<cr> 
map vsp :vsplit<cr>
map bhd :hide<cr> 
map bon :only<cr>
map bls :ls<cr>
map bsw :b 
map bd :bdelete<cr> 

nnoremap B ^
nnoremap E $
nnoremap $ <nop>
nnoremap ^ <nop>

" Text formatter
map <F7> mzgg=G`z
"
""
if has('langmap') && exists('+langnoremap')
	set langnoremap
endif

if has('mouse') && has('gui') "mouse+gui 
	set mouse=a
endif

"End of vimrc
