#Begin of ZSH Configuration
export ZSH="/home/stefanozzz123/.oh-my-zsh"
export TERM="xterm-256color"

export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LANG=it_IT.UTF-8

export EDITOR="vim" 

export ARCHFLAGS="-O2 -pipe -march=native -mtune=native"

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=50
SAVEHIST=50
setopt appendhistory autocd beep nomatch
unsetopt extendedglob
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/stefanozzz123/.zshrc'
zstyle ':completion:*' menu select
setopt completealiases

autoload -U compinit
compinit
# End of lines added by compinstall
export EDITOR="vim"
export PATH="/usr/lib/ccache/bin:/opt/bin:/usr/bin/eclipse:/usr/bin/sublime_text_2:/bin:/usr/bin"
export LDPATH="${LDPATH}"
export MANPATH="${MANPATH}"
export INFODIR="${INFODIR}"
export PAGER="less"
export CONFIG_PROTECT="${CONFIG_PROTECT}"
export CONFIG_PROTECT_MASK="${CONFIG_PROTECT_MASK}"
export TERM="xterm-256color"
export MANPATH="/usr/local/man:$MANPATH"

[[ -n "${key[PageUp]}"   ]]  && bindkey  "${key[PageUp]}"    history-beginning-search-backward
[[ -n "${key[PageDown]}" ]]  && bindkey  "${key[PageDown]}"  history-beginning-search-forward

#Left prompt
PROMPT="%{$fg_bold[red]%}(%m)%{$reset_color%} %{$fg_bold[green]%}%n%{$reset_color%} on %{$fg_bold[blue]%}%~%{$reset_color%} %{$fg[green]%}%#%{$reset_color%} "

#Right prompt
RPROMPT="%{$bg[yellow]%}%{$fg_bold[black]%}{return: %?}%{$reset_color%} %{$bg[blue]%}%{$fg_bold[yellow]%}[%l]%{$reset_color%}"

##Prompt Configuration##
autoload -U promptinit
promptinit

##Syntax Hightlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


##Small banner
#         <Hour:Minutes>      <Day/Month/Year> #
STARTDATE="$(date +%H:%M) on $(date +%d/%m/%y)"
terminalBanner(){
	clear
	printf "\033[32mHello\033[0m: $USER"
	printf "\nMachine's \033[33mhostname\033[0m: "; cat /etc/hostname
	printf "Running \033[33mShell\033[0m: $SHELL\n"
	printf "Running \033[33mKernel\033[0m: $(uname -s -r)\n\n"
	printf "\033[34m *\033[0m Shell online from: \033[34m$STARTDATE\033[0m\n"
}
##

#Aliases
##systemd
alias sdenable="sudo systemctl enable "
alias sdrestart="sudo systemctl restart "
alias sddisable="sudo systemctl disable "
alias sdstart="sudo systemctl start "
alias sdstop="sudo systemctl stop "
alias sdstatus="sudo systemctl status "
alias bootime="systemd-analyze time"
alias bootblame="systemd-analyze blame"
##Pacman
alias pacsync="sudo pacman -Sy"
alias pacget="sudo pacman -S "
alias pacrm="sudo pacman -R "
alias pacrmall="sudo pacman -Rsn "
alias pacdbopt="sudo pacman-db-upgrade; sudo pacman-optimize"
alias pacrmwdep="sudo pacman -Rsndd "
alias pacclean="sudo pacman -Scc "
alias pacsearch="pacman -Ss "
alias paclsearch="pacman -Qs "
alias pacdetail="pacman -Si "
alias pacldetail="pacman -Qi "
alias pacupg="sudo pacman -Syu" 
##Yaourt
alias yrtget="yaourt -S "
alias yrtrm="yaourt -R "
alias yrtrmall="yaourt -Rsn "
alias yrtsearch="yaourt -Ss "
alias yrtupgall="yaourt -Syuua"
alias yrtupg="yaourt -Syu"
#Check External IP 
alias wanip="curl ipecho.net/plain"
#i3
alias i3cfg="vim /home/stefanozzz123/.i3/config"
alias i3stcfg="sudo vim /etc/i3status_top.conf"
alias i3sbcfg="sudo vim /etc/i3status_bottom.conf"
#RaspPi
alias pissh="ssh 192.168.2.101 -p 22 -l "

terminalBanner
printf "\033[32m *\033[0m \033[32mReady\033[0m\n"

minecraft()
{
	printf "\033[32m*\033[0m Launching Minecraft...\n"
	java -jar /home/stefanozzz123/.bin/minecraft.jar
	clear
	printf "\n\033[34m*\033[0m Bye!\n"
}

scr()
{
		  if [[ $1 == "start" ]];
		  then
					 printf "\033[32m*\033[0m Starting auto mode.... HDMI1 should work now.\n"
					 xrandr --auto
					 if [[ $2 == "split" ]];
					 then

								xrandr --output HDMI1 --right-of LVDS1 & 
					 elif [[ $2 == "" ]];
					 then
								echo ""
					 fi
		  fi
		  if [[ $1 == "stop" ]];
		  then
					 printf "\033[31m*\033[0m Stopping output to HDMI1\n"
					 xrandr --output HDMI1 --off
		  fi
}
#End of ZSH configuration

