#Begin of ZSH Configuration
export ZSH="/home/stefanozzz123/.oh-my-zsh"
export TERM="xterm-256color"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export EDITOR="vim" 
export ARCHFLAGS="-O3 -pipe -march=native -mtune=native -Wall "

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=50
SAVEHIST=50
setopt appendhistory autocd beep nomatch
unsetopt extendedglob
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/stefanozzz123/.zshrc'
zstyle ':completion:*' menu select
setopt completealiases

autoload -U compinit
compinit
# End of lines added by compinstall
export EDITOR="vim"
export PATH="/home/stefanozzz123/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/ccache/bin:/opt/bin:/usr/bin/eclipse:/usr/bin/sublime_text_2:/bin:/usr/bin:${PATH}"
export LDPATH="${LDPATH}"
export MANPATH="${MANPATH}"
export INFODIR="${INFODIR}"
export PAGER="less"
export CONFIG_PROTECT="${CONFIG_PROTECT}"
export CONFIG_PROTECT_MASK="${CONFIG_PROTECT_MASK}"
export TERM="xterm-256color"
export MANPATH="/usr/local/man:$MANPATH"

[[ -n "${key[PageUp]}"   ]]  && bindkey  "${key[PageUp]}"    history-beginning-search-backward
[[ -n "${key[PageDown]}" ]]  && bindkey  "${key[PageDown]}"  history-beginning-search-forward



##Prompt Configuration##
#autoload -U promptinit
#promptinit

##Syntax Hightlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

PROMPT="%{$fg[yellow]%}[%T] %{$reset_color%}%{$fg_bold[red]%}(%m)%{$reset_color%} %{$fg_bold[green]%}%n%{$reset_color%} on %{$fg_bold[blue]%}%~%{$reset_color%} 
%{$fg[green]%}%#%{$reset_color%} %{$fg_bold[cyan]%}->%{$reset_color%} "

RPROMPT="%{$bg[green]%}%{$fg_bold[blue]%}Jobs: %j%{$reset_color%}%{$reset_color%}%{$bg[yellow]%}%{$fg_bold[black]%}return: %?%{$reset_color%}%{$bg[blue]%}%{$fg_bold[yellow]%}%l%{$reset_color%}"

##Small banner
START_DATE=$(date +%H:%M:%S)
banner()
{
   printf "Hi, \033[33m$(whoami)\033[0m\n"
	 printf "Hostname, \033[32m$(cat /etc/hostname)\033[0m\n"
   printf "OS: \033[31m$(uname -o -s -r)\033[0m\n"
   printf "IPv4: \033[34m$(ifconfig | grep inet | grep 192 | awk '{ print $2 }')\033[0m\n"
   printf "Shell: \033[35m$SHELL\033[0m\n"
   printf "RAM Usage: \033[31m$(free -m | grep Mem | awk '{ print $3 }')MB\033[0m\n\n"
   printf "New shell started on: \033[36m$START_DATE\033[0m\n\n"
}

##

#Aliases
##systemd
alias sdenable="sudo systemctl enable "
alias sdrestart="sudo systemctl restart "
alias sddisable="sudo systemctl disable "
alias sdstart="sudo systemctl start "
alias sdstop="sudo systemctl stop "
alias sdstatus="sudo systemctl status "
alias bootime="systemd-analyze time"
alias bootblame="systemd-analyze blame"
##Pacman
alias pacsync="sudo pacman -Sy"
alias pacget="sudo pacman -S "
alias pacrm="sudo pacman -R "
alias pacrmall="sudo pacman -Rsn "
alias pacdbopt="sudo pacman-db-upgrade; sudo pacman-optimize"
alias pacrmwdep="sudo pacman -Rsndd "
alias pacclean="sudo pacman -Scc "
alias pacsearch="pacman -Ss "
alias paclsearch="pacman -Qs "
alias pacdetail="pacman -Si "
alias pacldetail="pacman -Qi "
alias pacupg="sudo pacman -Syu" 
##Yaourt
alias yrtget="yaourt -S "
alias yrtrm="yaourt -R "
alias yrtrmall="yaourt -Rsn "
alias yrtsearch="yaourt -Ss "
alias yrtupgall="yaourt -Syuua"
alias yrtupg="yaourt -Syu"
#Check External IP 
alias wanip="curl ipecho.net/plain"
#i3
alias i3cfg="vim /home/stefanozzz123/.i3/config"
alias i3stcfg="sudo vim /etc/i3status_top.conf"
alias i3sbcfg="sudo vim /etc/i3status_bottom.conf"
#RaspPi
alias pissh="ssh 192.168.2.100 -p 22 -l "
alias piscan="ssh root@192.168.2.100 -p 22 scan "
#OpenVPN to raspPi
alias piovpnrem="sudo openvpn --config $HOME/Documenti/pivpnrem.ovpn --writepid /var/run/ovpn.pid"
alias piovpnloc="sudo openvpn --config $HOME/Documenti/pivpn.ovpn --writepid /var/run/ovpn.pid"
#NetworkManager GUI
alias nmgui="nm-connection-editor"
#TMux new
alias tmuxnew="tmux new-session -c $HOME -n Main:Zsh -s "

banner

scr()
{
		  if [[ $1 == "start" ]];
		  then
					 printf "\033[32m*\033[0m Starting auto mode.... HDMI1 should work now.\n"
					 xrandr --auto
					 if [[ $2 == "split" ]];
					 then

								xrandr --output HDMI1 --right-of LVDS1 & 
					 elif [[ $2 == "" ]];
					 then
								echo ""
					 fi
		  fi
		  if [[ $1 == "stop" ]];
		  then
					 printf "\033[31m*\033[0m Stopping output to HDMI1\n"
					 xrandr --output HDMI1 --off
		  fi
}

#End of ZSH configuration

